---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: admin-credentials
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: "admin123!@#"
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: database-credentials
type: Opaque
stringData:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: "keycloak_db_pass_123"
  KC_DB_URL: "jdbc:postgresql://keycloak-postgres:5432/keycloak"
  KC_DB_USERNAME: keycloak
  KC_DB_PASSWORD: "keycloak_db_pass_123"
