apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devenv

resources:
- vscode-sandbox.yaml

labels:
- pairs:
    app.kubernetes.io/name: vscode-gemini
    app.kubernetes.io/part-of: agent-sandbox-platform
    app.kubernetes.io/managed-by: kustomize
