apiVersion: v1
kind: Service
metadata:
  name: boundary-controller-api
  namespace: boundary
  labels:
    app: boundary-controller
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: 9200
      name: api
    - port: 9203
      targetPort: 9203
      name: ops
  selector:
    app: boundary-controller

---
apiVersion: v1
kind: Service
metadata:
  name: boundary-controller-cluster
  namespace: boundary
  labels:
    app: boundary-controller
spec:
  type: ClusterIP
  ports:
    - port: 9201
      targetPort: 9201
      name: cluster
  selector:
    app: boundary-controller

---
apiVersion: v1
kind: Service
metadata:
  name: boundary-worker
  namespace: boundary
  labels:
    app: boundary-worker
spec:
  type: ClusterIP
  ports:
    - port: 9202
      targetPort: 9202
      name: proxy
    - port: 9203
      targetPort: 9203
      name: ops
  selector:
    app: boundary-worker
