apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devenv

resources:
- claude-code-sandbox.yaml
- service.yaml

labels:
- pairs:
    app.kubernetes.io/name: claude-code-sandbox
    app.kubernetes.io/part-of: agent-sandbox-platform
    app.kubernetes.io/managed-by: kustomize
