apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
  - 01-namespace.yaml
  - 03-configmap.yaml
  - 04-rbac.yaml
  - 05-statefulset.yaml
  - 06-service.yaml
  - 07-ingress.yaml
  - 08-tls-secret.yaml

labels:
  - pairs:
      app.kubernetes.io/name: vault
      app.kubernetes.io/component: secrets-management
